version: '3.3'
services:
    mysql:
        ports:
            - '3306:3306'
        container_name: mysql
        volumes:
            - '/data/mysql/data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        image: mysql:5.7
